"""Business input schemas for StrategixAI.

This module defines validated contracts for strategic business assumptions.
The simulation engine, analytics pipeline, AI advisor, and Streamlit dashboard
should treat these models as the source of truth for user-provided business
inputs.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


NonNegativeFloat = Annotated[float, Field(ge=0.0)]
PositiveFloat = Annotated[float, Field(gt=0.0)]
Rate = Annotated[float, Field(ge=0.0, le=1.0)]
PositiveInt = Annotated[int, Field(gt=0)]
NonNegativeInt = Annotated[int, Field(ge=0)]


class BusinessSchema(BaseModel):
    """Base schema with strict validation behavior for business contracts."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
    )


class BusinessStage(StrEnum):
    """Lifecycle stage of the company being simulated."""

    IDEA = "idea"
    PRE_REVENUE = "pre_revenue"
    EARLY_STAGE = "early_stage"
    GROWTH = "growth"
    SCALE_UP = "scale_up"
    MATURE = "mature"


class RevenueModel(StrEnum):
    """Commercial model used to generate revenue."""

    SUBSCRIPTION = "subscription"
    USAGE_BASED = "usage_based"
    TRANSACTIONAL = "transactional"
    ONE_TIME_SALE = "one_time_sale"
    MARKETPLACE = "marketplace"
    HYBRID = "hybrid"


class PricingModel(StrEnum):
    """Primary pricing architecture for the business."""

    FLAT_RATE = "flat_rate"
    TIERED = "tiered"
    PER_SEAT = "per_seat"
    USAGE_BASED = "usage_based"
    FREEMIUM = "freemium"
    ENTERPRISE_CUSTOM = "enterprise_custom"


class MarketingChannel(StrEnum):
    """Acquisition channel categories used in growth assumptions."""

    PAID_SEARCH = "paid_search"
    PAID_SOCIAL = "paid_social"
    CONTENT = "content"
    SEO = "seo"
    PARTNERSHIPS = "partnerships"
    SALES_OUTBOUND = "sales_outbound"
    REFERRALS = "referrals"
    EVENTS = "events"
    MARKETPLACE = "marketplace"
    OTHER = "other"


class CustomerSegment(BusinessSchema):
    """Target customer segment with basic economic assumptions."""

    name: str = Field(min_length=1, max_length=120)
    description: str | None = Field(default=None, max_length=600)
    starting_customers: NonNegativeInt = Field(
        default=0,
        description="Initial active customers in this segment.",
    )
    average_contract_value: NonNegativeFloat = Field(
        description="Average annual contract value or annualized customer revenue.",
    )
    gross_margin: Rate = Field(
        default=0.75,
        description="Gross margin for revenue generated by this segment.",
    )


class PricingTier(BusinessSchema):
    """A reusable pricing tier for subscription, usage, or hybrid models."""

    name: str = Field(min_length=1, max_length=80)
    monthly_price: NonNegativeFloat = Field(
        description="Published monthly price for the tier.",
    )
    expected_customer_mix: Rate = Field(
        description="Expected share of customers assigned to this tier.",
    )
    included_usage_units: NonNegativeInt | None = Field(
        default=None,
        description="Included usage allowance before overage pricing applies.",
    )
    overage_unit_price: NonNegativeFloat | None = Field(
        default=None,
        description="Incremental unit price for usage above the included allowance.",
    )

    @model_validator(mode="after")
    def validate_usage_pricing(self) -> "PricingTier":
        """Require an overage price when a tier includes a usage allowance."""

        if self.included_usage_units is not None and self.overage_unit_price is None:
            raise ValueError("overage_unit_price is required when included_usage_units is set")
        return self


class PricingStrategy(BusinessSchema):
    """Pricing strategy assumptions used by simulations and advisory modules."""

    model: PricingModel
    currency: str = Field(default="USD", min_length=3, max_length=3)
    base_monthly_price: NonNegativeFloat = Field(
        description="Default monthly customer price before discounts or expansion.",
    )
    annual_discount_rate: Rate = Field(
        default=0.0,
        description="Discount applied to annual prepaid contracts.",
    )
    expected_expansion_rate: Rate = Field(
        default=0.0,
        description="Monthly expansion revenue rate from existing customers.",
    )
    tiers: tuple[PricingTier, ...] = Field(
        default_factory=tuple,
        description="Optional pricing tiers for tiered or hybrid pricing.",
    )

    @field_validator("currency")
    @classmethod
    def normalize_currency(cls, value: str) -> str:
        """Normalize ISO-style currency codes."""

        return value.upper()

    @model_validator(mode="after")
    def validate_tier_mix(self) -> "PricingStrategy":
        """Ensure tier mix is coherent when tiered pricing is provided."""

        if self.tiers:
            mix_total = sum(tier.expected_customer_mix for tier in self.tiers)
            if abs(mix_total - 1.0) > 0.01:
                raise ValueError("pricing tier customer mix must sum to approximately 1.0")
        return self


class ChannelAssumption(BusinessSchema):
    """Acquisition economics for a marketing or sales channel."""

    channel: MarketingChannel
    monthly_budget: NonNegativeFloat = Field(
        description="Monthly spend allocated to this channel.",
    )
    cost_per_acquisition: PositiveFloat = Field(
        description="Expected cost to acquire one paying customer.",
    )
    conversion_rate: Rate = Field(
        description="Lead-to-customer conversion rate for the channel.",
    )
    monthly_budget_growth_rate: Rate = Field(
        default=0.0,
        description="Expected month-over-month budget growth rate.",
    )


class MarketingStrategy(BusinessSchema):
    """Customer acquisition assumptions for go-to-market planning."""

    channels: tuple[ChannelAssumption, ...] = Field(
        default_factory=tuple,
        description="Channel-level acquisition plans.",
    )
    organic_monthly_leads: NonNegativeInt = Field(
        default=0,
        description="Leads expected without direct paid acquisition spend.",
    )
    organic_conversion_rate: Rate = Field(
        default=0.0,
        description="Organic lead-to-customer conversion rate.",
    )
    referral_rate: Rate = Field(
        default=0.0,
        description="Monthly customer referral rate from the active customer base.",
    )

    @model_validator(mode="after")
    def validate_channel_uniqueness(self) -> "MarketingStrategy":
        """Prevent duplicate channel assumptions in a single strategy."""

        channels = [assumption.channel for assumption in self.channels]
        if len(channels) != len(set(channels)):
            raise ValueError("marketing channels must be unique")
        return self


class ChurnAssumptions(BusinessSchema):
    """Retention and churn assumptions for customer and revenue forecasting."""

    monthly_logo_churn_rate: Rate = Field(
        description="Share of customers expected to churn each month.",
    )
    monthly_revenue_churn_rate: Rate = Field(
        description="Share of recurring revenue expected to churn each month.",
    )
    reactivation_rate: Rate = Field(
        default=0.0,
        description="Share of churned customers expected to reactivate monthly.",
    )
    churn_improvement_rate: Rate = Field(
        default=0.0,
        description="Monthly reduction rate in churn from retention improvements.",
    )


class CostStructure(BusinessSchema):
    """Operating cost assumptions used for profitability and runway analysis."""

    monthly_fixed_costs: NonNegativeFloat = Field(
        description="Baseline monthly operating costs.",
    )
    variable_cost_per_customer: NonNegativeFloat = Field(
        default=0.0,
        description="Monthly servicing cost per active customer.",
    )
    gross_margin: Rate = Field(
        default=0.75,
        description="Blended gross margin before operating expenses.",
    )
    headcount_growth_rate: Rate = Field(
        default=0.0,
        description="Expected month-over-month operating cost growth from hiring.",
    )


class BusinessAssumptions(BusinessSchema):
    """Complete business assumption set for a simulation scenario."""

    business_name: str = Field(min_length=1, max_length=160)
    stage: BusinessStage
    revenue_model: RevenueModel
    starting_cash_balance: NonNegativeFloat = Field(
        default=0.0,
        description="Available cash at the beginning of the simulation.",
    )
    starting_customers: NonNegativeInt = Field(
        default=0,
        description="Initial active paying customers.",
    )
    target_monthly_growth_rate: Rate = Field(
        description="Expected monthly growth rate for the active customer base.",
    )
    customer_segments: tuple[CustomerSegment, ...] = Field(default_factory=tuple)
    pricing: PricingStrategy
    marketing: MarketingStrategy
    churn: ChurnAssumptions
    costs: CostStructure

    @model_validator(mode="after")
    def validate_customer_baseline(self) -> "BusinessAssumptions":
        """Ensure segment counts are aligned with the stated customer baseline."""

        segment_customers = sum(segment.starting_customers for segment in self.customer_segments)
        if self.customer_segments and segment_customers != self.starting_customers:
            raise ValueError("customer segment starting_customers must equal starting_customers")
        return self
