"""Strategic intelligence schemas for StrategixAI.

These contracts describe deterministic executive intelligence generated from
simulation outputs. They intentionally contain no model, prompt, or API logic.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, model_validator


Score = Annotated[int, Field(ge=0, le=100)]


class IntelligenceSchema(BaseModel):
    """Base schema with strict validation for strategic intelligence outputs."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        validate_assignment=True,
    )


class HealthClassification(StrEnum):
    """Business health bands used for executive classification."""

    EXCELLENT = "Excellent"
    STRONG = "Strong"
    STABLE = "Stable"
    RISKY = "Risky"
    CRITICAL = "Critical"


class HealthScoreComponent(IntelligenceSchema):
    """One explainable component of the business health score."""

    name: str = Field(min_length=1, max_length=80)
    score: Score
    weight: Annotated[float, Field(gt=0.0, le=1.0)]
    explanation: str = Field(min_length=1, max_length=500)


class StrategicSignalCategory(StrEnum):
    """Supported signal categories for Phase 6 intelligence."""

    GROWTH = "Growth Signals"
    RISK = "Risk Signals"
    EFFICIENCY = "Efficiency Signals"
    CASH = "Cash Signals"


class SignalSeverity(StrEnum):
    """Executive signal direction."""

    POSITIVE = "positive"
    NEUTRAL = "neutral"
    WARNING = "warning"
    CRITICAL = "critical"


class StrategicSignal(IntelligenceSchema):
    """One deterministic strategic signal from simulation evidence."""

    category: StrategicSignalCategory
    severity: SignalSeverity
    title: str = Field(min_length=1, max_length=120)
    message: str = Field(min_length=1, max_length=500)
    metric: str = Field(min_length=1, max_length=80)


class RiskRadarCategory(StrEnum):
    """Risk radar dimensions required for Phase 6."""

    GROWTH = "Growth Risk"
    PROFITABILITY = "Profitability Risk"
    RUNWAY = "Runway Risk"
    RETENTION = "Retention Risk"


class RiskLevel(StrEnum):
    """Risk level where Critical is the highest concern."""

    LOW = "Low"
    MODERATE = "Moderate"
    HIGH = "High"
    CRITICAL = "Critical"


class RiskRadarItem(IntelligenceSchema):
    """One risk dimension with score and deterministic rationale."""

    category: RiskRadarCategory
    risk_score: Score = Field(description="0 is lowest risk; 100 is highest risk.")
    level: RiskLevel
    rationale: str = Field(min_length=1, max_length=500)


class RecommendedAction(IntelligenceSchema):
    """Highest-priority action generated by the intelligence service."""

    priority: Annotated[int, Field(ge=1, le=3)]
    title: str = Field(min_length=1, max_length=120)
    rationale: str = Field(min_length=1, max_length=500)
    expected_impact: str = Field(min_length=1, max_length=300)


class ScenarioWinnerAnalysis(IntelligenceSchema):
    """Explanation of why the winning scenario wins."""

    winner_name: str = Field(min_length=1, max_length=160)
    confidence_score: Score
    winning_dimensions: tuple[str, ...] = Field(min_length=1, max_length=6)
    rationale: str = Field(min_length=1, max_length=700)
    tradeoffs: str = Field(min_length=1, max_length=700)


class StrategicIntelligenceOutput(IntelligenceSchema):
    """Complete Phase 6 deterministic intelligence output."""

    scenario_id: str = Field(min_length=1, max_length=120)
    business_health_score: Score
    health_classification: HealthClassification
    score_components: tuple[HealthScoreComponent, ...] = Field(min_length=5, max_length=5)
    strategic_signals: tuple[StrategicSignal, ...] = Field(default_factory=tuple)
    executive_verdict: str = Field(min_length=1, max_length=900)
    recommended_actions: tuple[RecommendedAction, ...] = Field(min_length=1, max_length=3)
    risk_radar: tuple[RiskRadarItem, ...] = Field(min_length=4, max_length=4)
    scenario_winner_analysis: ScenarioWinnerAnalysis | None = None

    @model_validator(mode="after")
    def validate_required_risk_categories(self) -> "StrategicIntelligenceOutput":
        """Require exactly one item for each Phase 6 risk radar category."""

        categories = {item.category for item in self.risk_radar}
        if categories != set(RiskRadarCategory):
            raise ValueError("risk_radar must include every required risk category")
        return self
